version: '3.8'

services:
  app:
    container_name: car_care_backend
    build: .
    restart: always
    env_file:
      - .env
    networks:
      - car_care_net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: car_care_cloudflare
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    env_file:
      - .env
    depends_on:
      - app
    networks:
      - car_care_net

networks:
  car_care_net:
    external: true