version: '3.8'

services:
  app:
    container_name: django_car_care
    build: .
    restart: always
    env_file:
      - .env

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: django_cloudflare
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    env_file:
      - .env
    depends_on:
      - app