# Generated by Django 6.0.3 on 2026-03-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=24)),
                ('role', models.BooleanField(default=False)),
            ],
        ),
    ]
