# Generated by Django 6.0.3 on 2026-03-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_part_service_servicepart_vehicle_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
