# Generated by Django 6.0.3 on 2026-03-17 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_vehicle_license_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
