# Generated by Django 6.0.3 on 2026-03-22 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0004_vehicle_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_odometer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='purchase_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
