# Generated by Django 6.0.3 on 2026-03-22 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_alter_vehicle_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
