# Generated by Django 6.0.3 on 2026-03-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0006_alter_service_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='time',
            new_name='date',
        ),
    ]
