# Generated by Django 6.0.3 on 2026-03-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0007_rename_time_service_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='article_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
