# Generated by Django 6.0.3 on 2026-03-22 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0008_alter_part_article_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='vehicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service_app.vehicle'),
        ),
    ]
