# Generated by Django 6.0.3 on 2026-03-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0009_part_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='imaged_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
