# Generated by Django 6.0.3 on 2026-03-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0010_vehicle_imaged_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='imaged_data',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
