# Generated by Django 6.0.3 on 2026-03-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0011_alter_vehicle_imaged_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='imaged_data',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
